### ISSUE TITLE
Update Travis Env

### ISSUE THREAD

**Issue by dmlb2000** [pacifica/ansible-pacifica#15]
### Ansible Pacifica Role version
v0.2.0
### Pacifica Core Software versions
v1.0
### Platform Details
Any
### Scenario:
Travis environment should be updated to latest version so we can more accurately match deployment environments.

**Comment by dmlb2000** [comment]
Bump Python version to 3.8 and bump Travis dist to bionic

**Comment by GitBytes** [comment]
@dmlb2000 Are you thinking we should just do the similar thing to ansible-travis where we are testing against 3.6/3.7/3.8 scenarios? In addition should we maybe go to 3.8 as the default then or keep 3.6 and support up to 3.8?

**Comment by GitBytes** [comment]
@dmlb2000 Re-reading this I think you were just referring to the travis.yml config, at least for now.

I'll submit a new PR shortly.
