### ISSUE TITLE
Role performance with one of each service seems to have performance issues

### ISSUE THREAD

**Issue by GitBytes** [pacifica/ansible-pacifica#18]
Need to test a scenario where we deploy a whole set of services including but not limited to:
* metadata
* uniqueid
* policy
* ingest (front/back)
* cart (front/back)
* notifications (front/back)

I observed as I added services to the list the time it takes to run the tasks gets progressively longer. Needs testing and maybe some simplification to address the long run times.

**Comment by dmlb2000** [comment]
@GitBytes I agree with this here's some proof on the issue from Travis https://travis-ci.org/pacifica/ansible-pacifica/builds/632473468?utm_medium=notification&utm_source=github_status

**Comment by dmlb2000** [comment]
I think this got accidentally fixed at some point. The testing does take a while but the scenarios are auto-generated from a script now and the max any one scenario takes is 15 minutes. We just have bunches of scenarios...
