### ISSUE TITLE
This `default.yaml` doesn't exist

### ISSUE THREAD

**Issue by GitBytes** [pacifica/ansible-pacifica#29]
https://github.com/pacifica/ansible-pacifica/blob/bd78e4491b71f23f151ee18a98d205e3f7ef011e/tasks/vars.yml#L7

**Comment by dmlb2000** [comment]
The `default.yml` file may exist in many places it doesn't have to exist here.

If I recall correctly you can put the default.yaml into a consuming role or playbook and this role will pick it up and include it.

 * https://docs.ansible.com/ansible/latest/plugins/lookup.html
 * https://docs.ansible.com/ansible/latest/plugins/lookup/first_found.html
